name: github pages

on:
  push:
    paths: 
      - "docs/**"
    branches:
    - master

jobs:
  build-deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: sergioramos/yarn-actions/install@master
      with:
        frozen-lockfile: true
          
    - run: yarn
      
    - run: yarn build --version=2

    - run: yarn docs:build
      env:
        DOCS_BASE: /vue-composable/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/.vuepress/dist
