on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*"

name: Create Github Release

jobs:
  build:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true
          body: |
            Please refer to [CHANGELOG.md](https://github.com/pikax/vue-composable/blob/master/CHANGELOG.md) for details.
